name: luxuria_rentl_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_stripe:
  http: ^1.3.0
  carousel_slider: ^5.0.0
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  shared_preferences: ^2.0.0  # Replace with the latest version
  url_launcher: ^6.3.1
  intl: ^0.18.1 # Check for the latest 
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  webview_flutter_wkwebview: ^3.18.2
  video_player: ^2.4.5  # تأكد من استخدام أحدث إصدار متاح
  gif: ^2.3.0





dev_dependencies:

  flutter_native_splash: 
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icnos-2.png" # ضع مسار أيقونة التطبيق هنا
  adaptive_icon_background: "#000000" # خلفية الأيقونة في Android
  adaptive_icon_foreground: "assets/images/icnos-2.png" # للأيقونات التكيفية في Android






  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/
      - assets/images/luxuria-logo.png
      - assets/images/carDemo.png
      - assets/images/welcome.png
      - assets/images/promotions.png
      - assets/images/pic1.png
      - assets/icons/home.png
      - assets/icons/order.png
      - assets/icons/profile.png
      - assets/icons/wave.png
      - assets/icons/mingcute_notification-line.png
      - assets/images/categories/luxury.png
      - assets/images/categories/mid-range.png
      - assets/images/categories/economy.png
      - assets/images/categories/vans.png
      - assets/images/categories/sports.png
      - assets/icons/card.png
      - assets/icons/visa.png
      - assets/icons/mada.png
      - assets/images/icons.png
      - assets/images/logo-gif.gif
      


flutter_native_splash:
  color: "#000000" # لون الخلفية (يمكن تغييره حسب التصميم)
  image: assets/images/luxuria-logo.png # مسار الصورة التي ستظهر عند تشغيل التطبيق
  android: true
  ios: true
  fullscreen: true # يجعل صورة السلاش سكرين تمتد لكامل الشاشة


